language: ruby
rvm:
  - "2.1.5"

script: 'bundle exec rake spec:travis'

notifications:
  irc: "irc.freenode.org#ndlib"

bundler_args: --without development debug doc

before_install:
  - gem install bundler
