# Dear curious person:
#
# These are not the real keys to the kingdom. They are, however, used during
# development; Or more appropriately used as a frame of reference for our
# development.
#
# They are included so we can share what the keys should be.
default_email_from: 'sipity-development@nd.edu'
default_email_return_path: 'no-reply@nd.edu'
dragonfly_s3_access_key_id: 's3_key'
dragonfly_s3_bucket_name: 'bucket_name'
dragonfly_s3_root_path: 's3_root_dir'
dragonfly_s3_secret_access_key: 'secret'
dragonfly_s3_url_host: 'bucketname.aws.com'
dragonfly_secret: "e03509c7cbee4f602ba6cf4bb088bda4891efabfffb6f122cc1e20c7e807e8b8"
ezid_client_default_shoulder: "doi:10.5072/FK2"
ezid_client_password: apitest
ezid_client_user: apitest
hesburgh_api_auth_token: '12345'
hesburgh_api_host: https://api.library.nd.edu/
noid_pool: 'pool_name'
noid_port: '3000'
noid_server: 'noidserver.com'

development:
  domain_name: "localhost:3000"
  url_host: "http://localhost:3000"

test:
  domain_name: "localhost:3000"
  url_host: "http://localhost:3000"
