# Dear curious person:
#
# These are not the real keys to the kingdom. They are, however, used during
# development; Or more appropriately used as a frame of reference for our
# development.
#
# They are included so we can share what the keys should be.
airbrake_api_key: 'this-makes-no-sense'
airbrake_host: 'errbit.library.nd.edu'
cas_base_url: "https://login.nd.edu/cas"
cas_validate_url: "https://login.nd.edu/cas/serviceValidate"
curate_nd_url_for_etds: "https://curate.nd.edu/catalog?f_inclusive%5Bhuman_readable_type_sim%5D%5B%5D=Doctoral+Dissertation&f_inclusive%5Bhuman_readable_type_sim%5D%5B%5D=Master%27s+Thesis"
curate_nd_url_show_prefix_url: "https://curate.nd.edu/show/"
default_email_from: 'sipity-development@nd.edu'
default_email_return_path: 'no-reply@nd.edu'
dragonfly_s3_access_key_id: 's3_key'
dragonfly_s3_bucket_name: 'bucket_name'
dragonfly_s3_root_path: 's3_root_dir'
dragonfly_s3_path: "path"
dragonfly_s3_secret_access_key: 'secret'
dragonfly_s3_url_host: 'bucketname.aws.com'
dragonfly_secret: "12345"
ezid_client_default_shoulder: "doi:10.5072/FK2"
ezid_client_password: apitest
ezid_client_user: apitest
hesburgh_api_auth_token: '12345'
hesburgh_api_host: https://api.library.nd.edu/
noid_pool: 'pool_name'
noid_port: '3000'
noid_server: 'noidserver.com'
protocol: 'http'
sipity_access_key_for_batch_ingester: '1234'
sipity_access_key_for_etd_integrators: '4567'
sipity_batch_ingester_access_key: '1234' # deprecated
curate_batch_group_pid: "group_pid"
smtp_host: "smtp.gmail.com"
smtp_port: '587'
smtp_domain: "gmail.com"
smtp_authentication_type: "plain"
smtp_user_name: "noreply@nd.edu"
smtp_enable_starttls_auto: "true"
smtp_delivery_method: "smtp"
jira_password: "jira pwd"
jira_site_url: "jira url"
jira_username: "jira user"

development:
  domain_name: "localhost:3000"
  url_host: "http://localhost:3000"
  secret_key_base: 'bd6953190e19dabc215af75a5c856f584dca49a3ab729696946a80ec50f46094d4643d908b88b07011f898f5c6748f2ffa832c96bae409e5462f2cf3055f1ee7'
  cas_base_url: "https://cas.library.nd.edu/cas"
  cas_destination_url: "http://localhost:3000"
  cas_follow_url: "http://localhost:3000"
  curate_batch_user_pid: "batch_user_pid"
  curate_grad_school_editing_group_pid: "batch_group_pid"
  curate_batch_data_mount_path: "local/data"
  curate_batch_queue_mount_path: "local/queue"

test:
  domain_name: "localhost:3000"
  url_host: "http://localhost:3000"
  secret_key_base: 'bd6953190e19dabc215af75a5c856f584dca49a3ab729696946a80ec50f46094d4643d908b88b07011f898f5c6748f2ffa832c96bae409e5462f2cf3055f1ee7'
  curate_batch_user_pid: "batch_user_pid"
  curate_grad_school_editing_group_pid: "batch_group_pid"
  curate_batch_data_mount_path: "tmp/data"
  curate_batch_queue_mount_path: "tmp/queue"
