# Dear curious person:
#
# These are not the real keys to the kingdom. They are, however, used during
# development; Or more appropriately used as a frame of reference for our
# development.
#
# They are included so we can share what the keys should be.
DATABASE_PATH: db/development.sqlite3
dragonfly_secret: "e03509c7cbee4f602ba6cf4bb088bda4891efabfffb6f122cc1e20c7e807e8b8"
ldap_host: directory.example.com
ldap_port: '636'
ldap_encryption: simple_tls