creator: "dc:creator"
title: "dc:title"
alternate_title: "qualified_dc:title#alternate"
subject: "dc:subject"
abstract: "qualified_dc:description#abstract"
country: "qualifieddc_publisher#country"
advisor: "ths:relators"
contributor: "dc:contributor"
contributor_role: "ms:role"
date_created: "qualified_dc:date#created"
date_uploaded: "dc:dateSubmitted"
date_modified: "dc:modified"
language: "dc:language"
copyright: "dc:rights"
note: "qualified_dc:description#note"
publisher: "dc:publisher"
temporal_coverage: "qualified_dc:coverage#temporal"
spatial_coverage: "qualified_dc:coverage#spatial"
identifier.doi: "qualified_dc:identifier#doi"
urn: "qualified_dc:identifier#other"
defence_date: "dc:date"
date_approved: "qualified_dc:date#approved"
degree_name: "ms:name"
discipline: "ms:discipline"
degree_level: "ms:level"