creator: "dc:creator"
title: "dc:title"
alternate_title: "dc:title#alternate"
subject: "dc:subject"
abstract: "dc:description#abstract"
country: "dc:publisher#country"
advisor: "ths:relators"
contributor: "dc:contributor"
contributor_role: "ms:role"
date_created: "dc:date#created"
date_uploaded: "dc:dateSubmitted"
date_modified: "dc:modified"
language: "dc:language"
copyright: "dc:rights"
note: "dc:description#note"
publisher: "dc:publisher"
temporal_coverage: "dc:coverage#temporal"
spatial_coverage: "dc:coverage#spatial"
identifier.doi: "dc:identifier#doi"
urn: "dc:identifier#other"
defense_date: "dc:date"
date_approved: "dc:date#approved"
degree: "ms:degree"
degree_name: "ms:name"
program_name: "ms:discipline"
degree_level: "ms:level"
degree_level: "ms:level"