# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &development
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: <%= Figaro.env.domain_name %>
  secret_key_base: bd6953190e19dabc215af75a5c856f584dca49a3ab729696946a80ec50f46094d4643d908b88b07011f898f5c6748f2ffa832c96bae409e5462f2cf3055f1ee7
  ezid_client_default_shoulder: "doi:10.5072/FK2"
  ezid_client_user: apitest
  ezid_client_password: apitest

test:
  <<: *development
  domain_name: <%= Figaro.env.domain_name %>
  secret_key_base: 5c46a1f2503bc88be537850637b8a6fce653f02e48dd44dafd7bfc901787edcf53f3aa588224443ef3ecb6f0747f861aad2fcba0907e19c3abb592c1f856c7b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  admin_name: <%= Figaro.env.admin_name %>
  admin_email: <%= Figaro.env.admin_email %>
  admin_password: <%= Figaro.env.admin_password %>
  domain_name: <%= Figaro.env.domain_name %>
  secret_key_base: <%= Figaro.env.secret_key_base %>
  ezid_cloent_default_shoulder: <%= Figaro.env.ezid_client_default_shoulder %>
  ezid_client_user: <%= Figaro.env.ezid_client_user %>
  ezid_client_password: <%= Figaro.env.ezid_client_password %>

staging:
  <<: *production

pre_production:
  <<: *production
